apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: hostfile-builder
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"] 
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/scale"]
  verbs: ["get", "list", "update", "patch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-hostfiles
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountConfig.k8sName }} # Name is case sensitive
  namespace: default
roleRef:
  kind: Role
  name: hostfile-builder
  apiGroup: rbac.authorization.k8s.io
