{{ if .Values.serviceAccountConfig.gcpName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountConfig.k8sName }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccountConfig.gcpName }}
{{ end }}
